import { CENTER, SIZE, applyMove, draw, emptyBoard, key, makeBag, tileValue, validateMove } from "./rules.js";
const $ = (s) => document.querySelector(s);
const boardEl = $("#board"), rackEl = $("#human-rack"), statusEl = $("#status"), hintEl = $("#hint"), humanScoreEl = $("#human-score"), flyScoreEl = $("#fly-score"), neuronsEl = $("#neurons"), brainState = $("#brain-state"), sensory = $("#sensory"), candidatesEl = $("#candidates"), selectedEl = $("#selected"), submit = $("#submit-move"), clear = $("#clear-move"), swapModeButton = $("#swap-mode"), swapTilesButton = $("#swap-tiles"), fly = $("#fly");
let state, selectedRack = null, staged = [], dictionary = null, worker, exchangeMode = false, exchangeIndices = new Set();
const premium = new Map([["0:0","TW"],["0:7","TW"],["0:14","TW"],["7:0","TW"],["7:14","TW"],["14:0","TW"],["14:7","TW"],["14:14","TW"],["1:1","DW"],["2:2","DW"],["3:3","DW"],["4:4","DW"],["10:10","DW"],["11:11","DW"],["12:12","DW"],["13:13","DW"]]);
// A dense bilateral display layout for every node in the compact model.
// FlyWire's connection table has no neuron positions, so coordinates are
// schematic; each point's brightness is its corresponding recurrent value.
const NODES=2952, NODES_PER_REGION=NODES/4, goldenAngle=Math.PI*(3-Math.sqrt(5));
function lobe(cx,cy,rx,ry) { return Array.from({length:NODES_PER_REGION},(_,i)=>{ const radius=Math.sqrt((i+.5)/NODES_PER_REGION), angle=i*goldenAngle; return [cx+Math.cos(angle)*rx*radius,cy+Math.sin(angle)*ry*radius]; }); }
const neuronLayout=[...lobe(77,89,60,72),...lobe(141,89,49,68),...lobe(283,89,60,72),...lobe(219,89,49,68)];
let neuralCanvas, neuralTarget=new Float32Array(NODES).fill(.025), neuralCurrent=new Float32Array(NODES).fill(.025), neuralIgnitionAt=0, neuralFrame;
function setStatus(text) { statusEl.textContent = text; }
function drawNeuralField(time) { const ctx=neuralCanvas?.getContext("2d"); if(!ctx) return; const bounds=neuralCanvas.getBoundingClientRect(), scale=Math.min(devicePixelRatio||1,2), width=Math.round(bounds.width*scale), height=Math.round(bounds.height*scale); if(neuralCanvas.width!==width || neuralCanvas.height!==height) { neuralCanvas.width=width; neuralCanvas.height=height; } ctx.setTransform(scale,0,0,scale,0,0); ctx.clearRect(0,0,bounds.width,bounds.height); const sx=bounds.width/360, sy=bounds.height/178; for(let i=0;i<NODES;i++) { const [x,y]=neuronLayout[i], distance=Math.hypot(x-180,(y-89)*.74), reveal=neuralIgnitionAt ? Math.max(0,Math.min(1,(time-neuralIgnitionAt-distance*4.7)/430)) : 1, desired=.025+(neuralTarget[i]-.025)*reveal; neuralCurrent[i]+=(desired-neuralCurrent[i])*.055; const level=Math.min(1,Math.abs(neuralCurrent[i])), flicker=Math.max(0,level+(Math.sin(time*.009+i*2.17)+Math.sin(time*.015+i*.31))*.045*level), radius=.38+flicker*1.75; ctx.fillStyle=`hsla(${118-flicker*60} 88% ${25+flicker*58}% / ${.16+flicker*.82})`; ctx.beginPath(); ctx.arc(x*sx,y*sy,radius,0,Math.PI*2); ctx.fill(); if(flicker>.48) { ctx.fillStyle=`hsla(56 100% 75% / ${(flicker-.48)*.46})`; ctx.beginPath(); ctx.arc(x*sx,y*sy,radius*2.4,0,Math.PI*2); ctx.fill(); } } neuralFrame=requestAnimationFrame(drawNeuralField); }
function renderNeurons(activity = []) { if(!neuralCanvas) { neuralCanvas=document.createElement("canvas"); neuralCanvas.className="brain-field"; neuralCanvas.setAttribute("aria-hidden","true"); neuronsEl.replaceChildren(neuralCanvas); neuralFrame=requestAnimationFrame(drawNeuralField); } neuralIgnitionAt=activity.length===NODES ? performance.now() : 0; for(let i=0;i<NODES;i++) neuralTarget[i]=activity.length===NODES ? Math.min(1,Math.abs(activity[i])) : .025; }
function render() {
  boardEl.replaceChildren(); const stagedMap = new Map(staged.map((tile) => [key(tile.row, tile.col), tile]));
  for (let row=0; row<SIZE; row++) for (let col=0; col<SIZE; col++) {
    const square=document.createElement("button"), tile=state.board[row][col] || stagedMap.get(key(row,col));
    square.className=`square ${premium.get(key(row,col)) || ""} ${tile ? "occupied" : ""} ${row===CENTER && col===CENTER ? "center" : ""}`;
    square.setAttribute("role","gridcell"); square.innerHTML=tile ? `<b>${tile.letter}</b><small>${tile.blank ? 0 : tileValue(tile.letter)}</small>` : `<em>${premium.get(key(row,col)) || (row===CENTER && col===CENTER ? "✦" : "")}</em>`;
    square.onclick=()=>place(row,col); square.ondragover=(event)=>event.preventDefault(); square.ondrop=(event)=>{ event.preventDefault(); place(row,col,Number(event.dataTransfer.getData("text/plain"))); }; boardEl.append(square);
  }
  rackEl.replaceChildren(...state.humanRack.map((letter,index)=>{
    const tile=document.createElement("button"), used=staged.some((move)=>move.rackIndex===index); tile.className=`rack-tile ${selectedRack===index ? "selected" : ""} ${exchangeIndices.has(index) ? "exchange-selected" : ""} ${used ? "used" : ""}`;
    tile.innerHTML=`<b>${letter}</b><small>${tileValue(letter)}</small>`; tile.disabled=used; tile.draggable=!used && !exchangeMode; tile.ondragstart=(event)=>event.dataTransfer.setData("text/plain",String(index)); tile.onclick=()=>{ if(exchangeMode) exchangeIndices.has(index) ? exchangeIndices.delete(index) : exchangeIndices.add(index); else selectedRack=index; render(); }; return tile;
  }));
  humanScoreEl.textContent=state.humanScore; flyScoreEl.textContent=state.flyScore; submit.disabled=!staged.length || state.turn!=="human" || exchangeMode; clear.disabled=!staged.length;
  swapModeButton.disabled=state.turn!=="human" || state.bag.length<7 || staged.length>0; swapModeButton.textContent=exchangeMode ? "Cancel swap" : "Swap tiles"; swapTilesButton.hidden=!exchangeMode; swapTilesButton.disabled=!exchangeIndices.size; swapTilesButton.textContent=`Swap ${exchangeIndices.size || "selected"}`;
}
function place(row,col,rackIndex=selectedRack) { if(exchangeMode || state.turn!=="human" || rackIndex===null || !Number.isInteger(rackIndex) || state.board[row][col] || staged.some((move)=>move.row===row && move.col===col) || staged.some((move)=>move.rackIndex===rackIndex)) return; const source=state.humanRack[rackIndex], letter=source==="?" ? prompt("Blank tile: choose A-Z","E")?.toUpperCase() : source; if(!/^[A-Z]$/.test(letter || "")) return; staged.push({row,col,letter,blank:source==="?",rackIndex}); selectedRack=null; render(); }
function refill(which) { state[which].push(...draw(state.bag,7-state[which].length)); }
function shuffle(items) { for(let i=items.length-1;i>0;i--) { const j=Math.floor(Math.random()*(i+1)); [items[i],items[j]]=[items[j],items[i]]; } }
function exchangeRack(which,indices) { const discarded=[...indices].sort((a,b)=>b-a).map((index)=>state[which].splice(index,1)[0]); state[which].push(...draw(state.bag,discarded.length)); state.bag.push(...discarded); shuffle(state.bag); }
function swapHumanTiles() { if(!exchangeIndices.size || state.bag.length<7 || state.turn!=="human") return; const count=exchangeIndices.size; exchangeRack("humanRack",exchangeIndices); exchangeIndices=new Set(); exchangeMode=false; selectedRack=null; hintEl.textContent=`You swapped ${count} tile${count===1 ? "" : "s"}. The fly takes its turn.`; state.turn="fly"; render(); flyTurn(); }
function commitHuman() { const check=validateMove(state.board,staged,dictionary); if(!check.ok) { hintEl.textContent=check.message; return; } applyMove(state.board,staged); state.humanScore+=check.score; state.humanRack=state.humanRack.filter((_,i)=>!staged.some((move)=>move.rackIndex===i)); staged=[]; refill("humanRack"); hintEl.textContent=`You played ${check.words.join(" + ")} for ${check.score} points.`; state.turn="fly"; render(); flyTurn(); }
function flyTurn() { setStatus("The fly is considering its tiles…"); brainState.textContent="THINKING"; brainState.className="pill thinking"; fly.className="fly thinking"; sensory.textContent=`${state.board.flat().filter(Boolean).length} board cells + 7 rack inputs`; worker.postMessage({board:state.board,rack:state.flyRack,bagCount:state.bag.length}); }
function showFlyHand(tile) {
  const x=Math.round((tile.col+.5)/SIZE*1000), y=Math.round((tile.row+.5)/SIZE*1000);
  // A real fly leg does not make a single graphic zig-zag: it has tapered,
  // separately articulated sections, with the knee kicked slightly outward.
  const side=x<500 ? 1 : -1, start={x,y:-95}, knee={x:Math.max(42,Math.min(958,x+side*74)),y:Math.max(105,Math.round(y*.34))}, ankle={x:Math.max(42,Math.min(958,x-side*38)),y:Math.max(190,Math.round(y*.68))}, tip={x,y};
  const points=[start,knee,ankle,tip], widths=[[25,18],[19,13],[14,8]];
  const limb=(a,b,outerA,outerB)=>{ const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len; return `${a.x+nx*outerA},${a.y+ny*outerA} ${b.x+nx*outerB},${b.y+ny*outerB} ${b.x-nx*outerB},${b.y-ny*outerB} ${a.x-nx*outerA},${a.y-ny*outerA}`; };
  const bristles=points.slice(0,-1).flatMap((a,segment)=>{ const b=points[segment+1],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len; return [ .28,.48,.68,.82 ].map((t,i)=>{ const px=a.x+dx*t,py=a.y+dy*t,sign=(i+segment)%2?1:-1,reach=15+(i%2)*9; return `M ${px+nx*3*sign} ${py+ny*3*sign} l ${nx*reach*sign-dx/len*7} ${ny*reach*sign-dy/len*7}`; }); }).join(" ");
  const hand=document.createElement("div"); hand.className="fly-hand";
  hand.innerHTML=`<svg viewBox="0 0 1000 1000" aria-hidden="true"><g class="fly-limb"><g class="fly-leg-shadow">${points.slice(0,-1).map((a,i)=>`<polygon points="${limb(a,points[i+1],widths[i][0]+7,widths[i][1]+7)}"/>`).join("")}</g><g class="fly-leg-chitin">${points.slice(0,-1).map((a,i)=>`<polygon class="leg-section section-${i}" points="${limb(a,points[i+1],widths[i][0],widths[i][1])}"/>`).join("")}</g><path class="fly-arm-bristles" d="${bristles}"/><circle class="fly-joint" cx="${knee.x}" cy="${knee.y}" r="15"/><circle class="fly-joint" cx="${ankle.x}" cy="${ankle.y}" r="12"/><g class="fly-grip" transform="translate(${tip.x} ${tip.y})"><ellipse cx="0" cy="1" rx="13" ry="18"/><path d="M-10 8 L-25 29 M10 8 L25 29"/><rect x="-17" y="-18" width="34" height="34" rx="4"/><text x="0" y="8">${tile.letter}</text></g></g></svg>`;
  boardEl.append(hand);
  hand.animate([{transform:"translateY(-150%)",offset:0,easing:"cubic-bezier(.18,.72,.2,1)"},{transform:"translateY(0)",offset:.72},{transform:"translateY(0)",offset:.82,easing:"cubic-bezier(.55,0,.82,.3)"},{transform:"translateY(-150%)",offset:1}],{duration:2000,fill:"both"});
  setTimeout(()=>hand.remove(),2080);
}
function revealFlyTile(tile) { applyMove(state.board,[tile]); const square=boardEl.children[tile.row*SIZE+tile.col]; square.classList.add("occupied"); square.innerHTML=`<b>${tile.letter}</b><small>${tile.blank ? 0 : tileValue(tile.letter)}</small>`; }
function endFlyTurn() { state.turn="human"; setStatus("Your turn"); setTimeout(()=>{fly.className="fly resting";brainState.textContent="RESTING";},900); render(); }
function animateFlyMove(data) { let index=0; const completeMove=()=>{ state.flyScore+=data.score; const used=[...data.word]; state.flyRack=state.flyRack.filter((letter)=>{const at=used.indexOf(letter);if(at<0)return true;used.splice(at,1);return false;}); refill("flyRack"); selectedEl.textContent=`${data.word} · ${data.score} pts`; hintEl.textContent=`The fly plays ${data.word} for ${data.score} points.`; setTimeout(endFlyTurn,700); }; const placeNext=()=>{ const tile=data.move[index++]; showFlyHand(tile); setTimeout(()=>revealFlyTile(tile),1440); if(index<data.move.length) setTimeout(placeNext,2120); else setTimeout(completeMove,1510); }; placeNext(); }
function finishFly(data) { brainState.textContent="MOVED"; brainState.className="pill"; fly.className="fly active"; renderNeurons(data.activity); if(data.activity?.length===NODES) setTimeout(()=>renderNeurons(),1800); candidatesEl.textContent=`${data.candidates} legal plays · ${data.model || "fallback"}`; if(data.exchange) { exchangeRack("flyRack",data.exchangeIndices); selectedEl.textContent="SWAP"; hintEl.textContent=`The fly swaps ${data.exchangeIndices.length} tiles.`; endFlyTurn(); } else if(data.pass) { selectedEl.textContent="PASS"; hintEl.textContent="The fly passes."; endFlyTurn(); } else animateFlyMove(data); }
async function start() { setStatus("Loading the lexicon…"); const response=await fetch("public/data/words.txt"); if(!response.ok) throw new Error("Run npm run build:lexicon to create the game dictionary."); dictionary=new Set((await response.text()).trim().split(/\r?\n/)); state={board:emptyBoard(),bag:makeBag(),humanRack:[],flyRack:[],humanScore:0,flyScore:0,turn:"human"}; refill("humanRack"); refill("flyRack"); staged=[]; selectedRack=null; exchangeMode=false; exchangeIndices=new Set(); setStatus("Your turn"); hintEl.textContent="Choose or drag a tile to the board. Your first word must cross the center star."; renderNeurons(); render(); }
worker=new Worker("src/fly-worker.js",{type:"module"}); worker.onmessage=({data})=>data.type==="error" ? (setStatus(data.message),brainState.textContent="OFFLINE") : finishFly(data);
submit.onclick=commitHuman; clear.onclick=()=>{staged=[];selectedRack=null;render();}; swapModeButton.onclick=()=>{exchangeMode=!exchangeMode;exchangeIndices=new Set();selectedRack=null;hintEl.textContent=exchangeMode ? "Select tiles to swap, then press Swap selected." : "Swap cancelled.";render();}; swapTilesButton.onclick=swapHumanTiles; $("#new-game").onclick=()=>start().catch((error)=>setStatus(error.message)); start().catch((error)=>setStatus(error.message));
